# Exclude a variety of commonly ignored directories.
exclude = [
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "venv",
    "env",
    ".env",
    ".github",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.10
target-version = "py310"

# Ruff version = 0.9.7
required-version = "==0.9.7"

# Source dir is app
src = [".", "app"]

[lint]
select = [
    "E4", "E5", "E7", "E9", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # Pyflakes
    "FAST", # FastAPI
    "ANN", # flake8-annotations
    "ASYNC", # flake8-async
    "PIE794", # flake8-pie for duplicate class field
    "Q", # flake8-quotes
    "I", # isort
]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.flake8-annotations]
# __init__'s return type doesn't need to be annotated
mypy-init-return = true

# When a variable is just a dummy and won't be used,
# it doesn't have to be annotated
suppress-dummy-args = true

# When a function doesn't have a return statement
# or just returns None, the return type doesn't need to
# be annotated
suppress-none-returning = true

[lint.isort]
known-third-party = ["fastapi", "pydantic"]

[lint.pycodestyle]
ignore-overlong-task-comments = true
max-line-length = 100

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
