name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Update Version"]
    types: [completed]
    branches: [main, staging]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Get Git tag
        id: get-tag
        run: |
          GIT_TAG=$(git describe --tags --exact-match ${{ github.event.workflow_run.head_sha }} || echo "")
          if [ -z "$GIT_TAG" ]; then
            echo "No tag found for this commit."
            exit 1
          fi
          echo "Git tag: $GIT_TAG"
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ env.GIT_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
